version: "3"

services:
  nginx:
    image: nginx
    container_name: dashboard-backend-nginx
    volumes:
      - ./ci/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4444:80"
    depends_on:
      - web

  web:
    container_name: dashboard-backend-web
    build: .
    environment:
      - ENV=prod
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: dashboard-backend-db
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=dashboard
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db/prod:/var/lib/postgresql/data
