version: "3"

services:

  nginx:
    image: nginx
    container_name: dashboard-backend-nginx
    volumes:
      - ./ci/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    ports:
      - "4444:80"
    depends_on:
      - backend

  backend:
    container_name: dashboard-backend-backend
    build: .
    environment:
      - ENV=prod
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: dashboard-backend-db
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=dashboard
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD
    env_file:
      - docker.env
    volumes:
      - ./db/prod:/var/lib/postgresql/data
