version: "3"

services:

  nginx:
    image: nginx
    container_name: dashboard-backend-nginx
    volumes:
      - ./ci/nginx.conf:/etc/nginx/nginx.conf
      - django-static:/app/static/
    ports:
      - "4444:80"
    depends_on:
      - backend

  backend:
    container_name: dashboard-backend-backend
    build: .
    env_file:
      - .env_file
    environment:
      - ENV=prod
      - POSTGRES_PASSWORD
    expose:
      - "8000"
    volumes:
      - django-static:/app/static/
    depends_on:
      - db

  db:
    image: postgres
    container_name: dashboard-backend-db
    expose:
      - "5432"
    env_file:
      - .env_file
    environment:
      - POSTGRES_DB=dashboard
      - POSTGRES_USER=dashboard
      - POSTGRES_PASSWORD
    volumes:
      - ./db/prod:/var/lib/postgresql/data

volumes:
  django-static:
