# Generated by Django 3.0.4 on 2020-04-11 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20200411_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, default='', max_length=256)),
                ('keyword', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='enumcategory',
            name='img',
        ),
        migrations.AddField(
            model_name='enumcategory',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enums', to='bill.Icon'),
        ),
    ]
