# Generated by Django 3.0.4 on 2020-04-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_auto_20200411_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='keyword',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
