# Generated by Django 3.0.4 on 2020-04-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_auto_20200411_1924'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enumcategory',
            unique_together={('icon', 'name', 'category')},
        ),
    ]
