# Generated by Django 3.0.6 on 2020-05-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_auto_20200430_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringbill',
            name='skip_summary',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='skip_summary',
        ),
        migrations.AddField(
            model_name='recurringbill',
            name='skipForSummaryFlag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='skipForSummaryFlag',
            field=models.IntegerField(default=0),
        ),
    ]
