# Generated by Django 3.0.6 on 2020-05-30 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0008_auto_20200529_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurringbill',
            old_name='skipForSummaryFlag',
            new_name='skip_summary_flag',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='skipForSummaryFlag',
            new_name='skip_summary_flag',
        ),
    ]
