# Generated by Django 3.0.6 on 2020-06-16 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0011_auto_20200614_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enumcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='icon',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlybudget',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recurringbill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rbs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL),
        ),
    ]
