# Generated by Django 2.2.13 on 2020-07-03 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200627_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_password',
        ),
        migrations.AlterField(
            model_name='recurringbill',
            name='card',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'CAR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rb_cards', to='backend.EnumCategory'),
        ),
        migrations.AlterField(
            model_name='recurringbill',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'CAT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rb_categories', to='backend.EnumCategory'),
        ),
        migrations.AlterField(
            model_name='recurringbill',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'COM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rb_companies', to='backend.EnumCategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'CAR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_cards', to='backend.EnumCategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'CAT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_categories', to='backend.EnumCategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'COM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_companies', to='backend.EnumCategory'),
        ),
    ]
