# Generated by Django 2.2.13 on 2020-07-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200703_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_password',
            field=models.BooleanField(default=False),
        ),
    ]
