# Generated by Django 3.0.4 on 2020-03-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=32)),
                ('amount', models.FloatField()),
                ('category', models.CharField(max_length=32)),
                ('company', models.CharField(max_length=32)),
                ('card', models.CharField(max_length=32)),
                ('note', models.CharField(max_length=512)),
                ('time_created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
    ]
