# Generated by Django 3.0.4 on 2020-03-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnumCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(blank=True, default='', max_length=256)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.CharField(blank=True, default='Undefined Card', max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, default='Undefined Category', max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='company',
            field=models.CharField(blank=True, default='Undefined Company', max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='icon',
            field=models.CharField(blank=True, default='Undefined Icon', max_length=32),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
