# Generated by Django 3.0.4 on 2020-03-28 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0005_enumcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='card',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='company',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='icon',
            field=models.ForeignKey(limit_choices_to={'category': 'ICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restful.EnumCategory'),
        ),
    ]
