# Generated by Django 3.0.4 on 2020-03-28 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0006_auto_20200327_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(limit_choices_to={'category': 'CAR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_card', to='restful.EnumCategory'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category': 'CAT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_category', to='restful.EnumCategory'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(limit_choices_to={'category': 'COM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_company', to='restful.EnumCategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='icon',
            field=models.ForeignKey(limit_choices_to={'category': 'ICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_icon', to='restful.EnumCategory'),
        ),
    ]
