# Generated by Django 3.0.4 on 2020-03-29 18:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0007_auto_20200327_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='enumcategory',
            options={'ordering': ['category']},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='icon',
        ),
        migrations.AlterField(
            model_name='enumcategory',
            name='category',
            field=models.CharField(choices=[('CAT', 'Category'), ('COM', 'Company'), ('CAR', 'Card'), ('NUL', 'NULL')], default='NUL', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
