# Generated by Django 3.0.4 on 2020-04-04 06:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0008_auto_20200329_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(limit_choices_to={'category': 'CAR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_bill_card', to='restful.EnumCategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(limit_choices_to={'category': 'CAT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_bill_category', to='restful.EnumCategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(limit_choices_to={'category': 'COM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_bill_company', to='restful.EnumCategory'),
        ),
        migrations.CreateModel(
            name='RecurringBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('Y', 'Year'), ('M', 'Month')], default='M', max_length=1)),
                ('recurring_month', models.IntegerField()),
                ('recurring_day', models.IntegerField()),
                ('amount', models.FloatField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=512)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('card', models.ForeignKey(limit_choices_to={'category': 'CAR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_recur_card', to='restful.EnumCategory')),
                ('category', models.ForeignKey(limit_choices_to={'category': 'CAT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_recur_category', to='restful.EnumCategory')),
                ('company', models.ForeignKey(limit_choices_to={'category': 'COM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_recur_company', to='restful.EnumCategory')),
            ],
        ),
    ]
