# Generated by Django 3.0.4 on 2020-04-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0009_auto_20200403_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringbill',
            options={'ordering': ['frequency', 'recurring_month', 'recurring_day', 'time_created']},
        ),
        migrations.AlterField(
            model_name='recurringbill',
            name='recurring_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
