# Generated by Django 3.0.4 on 2020-04-04 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restful', '0011_auto_20200403_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringbill',
            name='card',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'CAR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_recur_card', to='restful.EnumCategory'),
        ),
        migrations.AlterField(
            model_name='recurringbill',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'CAT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_recur_category', to='restful.EnumCategory'),
        ),
        migrations.AlterField(
            model_name='recurringbill',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'COM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_recur_company', to='restful.EnumCategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'CAR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_bill_card', to='restful.EnumCategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'CAT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_bill_category', to='restful.EnumCategory'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'COM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_bill_company', to='restful.EnumCategory'),
        ),
    ]
